### ISSUE TITLE
folder name in appendix doesn't reflect the repo name

### ISSUE THREAD

**Issue by firmread** [patriciogonzalezvivo/thebookofshaders#1]
Thanks for awesome book Patricio!

I found a small typo but potentially crucial for newbies w/o git knowledge on [appendix](https://github.com/patriciogonzalezvivo/thebookofshaders/tree/013d9d3d0ebb446aa7975c8e7ab922b7392df501/90)
```
cd ~
git clone https://github.com/patriciogonzalezvivo/thebookofshaders.git
cd GLSL-Book
python -m SimpleHTTPServer
```
should be 
```
cd ~
git clone https://github.com/patriciogonzalezvivo/thebookofshaders.git
cd thebookofshaders
python -m SimpleHTTPServer
```

**Comment by patriciogonzalezvivo** [comment]
Hi Firm! Thanks so much! I just change it! Let me know if you see another mistake
