### ISSUE TITLE
Unable to load picture or PDF file 'matrixes.png'

### ISSUE THREAD

**Issue by pauloguerraf** [patriciogonzalezvivo/thebookofshaders#10]
Hello there,

I am trying to compile the book into a pdf but I am getting the following error:

Successful building of ./book.tex
pandoc: Could not find image `matrixes.png', skipping...
! Unable to load picture or PDF file 'matrixes.png'.
<to be read again> 
                   }
l.2658 .../Matrix}{\includegraphics{matrixes.png}}

pandoc: Error producing PDF from TeX source
Error in building of ./book.pdf

Any advice on how to solve it, would be truly appreciated. Thank you.

Paulo

**Comment by patriciogonzalezvivo** [comment]
Hi! Seams that is not generating the images. Did you install glslViewer? is working properly?

**Comment by pauloguerraf** [comment]
Hi!

Yes. I installed glslViewer. And it seems to be working properly. I have attached a screenshot of the terminal when it starts generating the images, just in case... 

Best,

Paulo

<img width="813" alt="screen shot 2015-07-17 at 6 55 25 am" src="https://cloud.githubusercontent.com/assets/1149371/8746658/3fb63264-2c51-11e5-997b-740254518e4a.png">

**Comment by patriciogonzalezvivo** [comment]
You are right! in fact matrixes.png is not generated... is there... seam doesn't like the format. I will try to change it this weekend. Thanks

**Comment by cansik** [comment]
Would be great if you could provide a pdf download (even it is not the newest). I can't build it on MacOSX because glslViewer is not working / building and it's a bit inconvenient to install so much dependencies to generate a pdf.

**Comment by cansik** [comment]
I fixed this in my last issue I opened #13 it is a parsing / generation failure of the tmp.md
