### ISSUE TITLE
Circle function question

### ISSUE THREAD

**Issue by youandhubris** [patriciogonzalezvivo/thebookofshaders#11]
Hi there, I only had time to quickly glance through the book, but from what I've seen, really really really nice work! : )

This is not exactly an issue, it's more a doubt. Regarding the circle function, I usually use a distance function. Something like this:

> float circle(vec2 _st, float _radius ){
  float dist = distance(vec2(0.5), _st);
float smooth = _radius*0.05;
  return 1.-smoothstep(_radius-smooth,_radius+smooth, dist);
}

This way, you know that your radius values equals the tile size. So instead of having an approximation, you have an exact value. 
If radius == 1., you fill everything; if radius == 0.5, you exactly match the tile border; and so on.
At least for me, it looks simple.

So, my question is, why did you do it like that? Thanks for your time! : )

**Comment by patriciogonzalezvivo** [comment]
Hi @youandhubris, I usually try to avoid distance() functions. They use sqrt() and is very expensive in terms of performance

**Comment by patriciogonzalezvivo** [comment]
Here is an interesting link to read: http://www.java-gaming.org/index.php?topic=28018.0
