### ISSUE TITLE
Animating (Rotating) Polar Shapes

### ISSUE THREAD

**Issue by mattrei** [patriciogonzalezvivo/thebookofshaders#15]
Hi, 

in chapter _Shapes_ in subchapter _Polar shapes_ I want to animate the function.
This is done by adding u_time to the x variable in the Graph plotter, for instance
```javascript
y = cos((x+u_time)*3.);
```
This is fine, however when I want to drive it more quickly.
```javascript
y = cos((x+u_time * 4. )*3.);
```
I get very weird results. Seems that the cosinus function return wrong values. Why is this so?!

Thanks,
Matthias

**Comment by patriciogonzalezvivo** [comment]
Hi Matthias,

What computer are you using? What graphic card do you have? How long did your code was running? I did this, and looks like this on my side:

![00](https://cloud.githubusercontent.com/assets/346914/9007185/f18c2b86-375c-11e5-9002-76fa76acb364.gif)

Can you Show how it looks like on your computer? Graphics cards sometimes react differently, Manufactures have to follow the GLSL specs only in the define behavior. Usually Nvidia cards are more permissive and robust, the less fancy is the graphic card the less robust and "friend" will react.

**Comment by mattrei** [comment]
I have a Intel HD 4000  and I am running on Linux with _OpenGL version string: 3.0 Mesa 10.5.2_ .

I tried it right now again to make a screenshot and it suddenly it works. I tell you the truth in this very afternoon and some days before the sinus was very corrupted.

I thought it may be an API restriction, but it is definitely a graphic driver issue. Or probably it was an browser issue or my system was too loaded?!?

Anyway thanks for your quick response and your clarification!!
