### ISSUE TITLE
y = rand(x) behaviour around x = PI

### ISSUE THREAD

**Issue by Spaxe** [patriciogonzalezvivo/thebookofshaders#16]
Reading the excellent book, I saw this plot on my Mac OS X 10.11:

<img width="774" alt="screen shot 2015-08-26 at 11 23 20" src="https://cloud.githubusercontent.com/assets/708395/9483545/1b28acc0-4be5-11e5-9735-617fe9eb62dc.png">

There are two bits where rand() has a strange distribution favouring the edges, x = PI and -PI. Does anyone else see this, and why is it?

**Comment by patriciogonzalezvivo** [comment]
Hello, good eye! that's totally correct! 
The random function is using the equation described just above that example. The random is obtain with the fractal of a sin() curve ( ```y = fract(sin(x)*1.0);``` ). That's why close to the edges of the wave (at PI, -PI and every other phase of PI) the curve is actually visible.

**Comment by Spaxe** [comment]
Oh, that's interesting. Good to know!
