### ISSUE TITLE
Chapters 15 and 16 not linked on main page

### ISSUE THREAD

**Issue by kasperkamperman** [patriciogonzalezvivo/thebookofshaders#188]
I've found them in Google, however they are not linked on the main page. 

https://thebookofshaders.com/15/
https://thebookofshaders.com/16/

I hope you will continue with the book, because it's really a great resource that explains shaders in an understandable way.

**Comment by patriciogonzalezvivo** [comment]
Hi! thanks so much! Yes those chapters need to be review and edited before linked to the index.

I haven't had free time to do it. But thanks for the heads up : )

Patricio
