### ISSUE TITLE
Chapter 04: shaders in Processing

### ISSUE THREAD

**Issue by codeanticode** [patriciogonzalezvivo/thebookofshaders#2]
In the section about shaders in Processing (chapter 4), you mention the use of the PROCESSING_COLOR_SHADER define. As of 2.2.1 and 3.0+, those defines are no longer needed, since Processing automatically determines the shader "type".

**Comment by patriciogonzalezvivo** [comment]
That's a great! good to know! should I take it out or make a comment about it? Gracias Andres!! : )

**Comment by codeanticode** [comment]
The automatic type detection was implemented in 2.1, so you can mention that the defines are still needed if you are running older versions.

**Comment by patriciogonzalezvivo** [comment]
fixed :) 
Thanks Andres!
