### ISSUE TITLE
Can't make PDF on MacOS El Capitan 10.11.6

### ISSUE THREAD

**Issue by benhdkn** [patriciogonzalezvivo/thebookofshaders#205]
Hi, 

I've been struggling with the process of making a PDF out of the repo. I followed every steps described on the appendix 'How to print this book' and still can't make it work. Any help appreciated. Thanks

Occurring right after the making of the shader images:

`Generating ./book.pdf from:
	./00/tmp.md
	./01/tmp.md
	./02/tmp.md
	./03/tmp.md
	./04/tmp.md
	./05/tmp.md
	./06/tmp.md
	./07/tmp.md
	./08/tmp.md
	./09/tmp.md
	./10/tmp.md
	./11/tmp.md
	./12/tmp.md
	./13/tmp.md
	./14/tmp.md
	./15/tmp.md
	./16/tmp.md
	./17/tmp.md
	./18/tmp.md
	./appendix/tmp.md
	./examples/tmp.md
	./glossary/tmp.md
Using the following flags:
	-N
	--smart
	--no-tex-ligatures
	--toc
	--standalone
	--preserve-tabs
	-V documentclass=scrbook
	-V papersize=a4
	-V links-as-note
	-S
	--latex-engine=xelatex
Traceback (most recent call last):
  File "src/parseBook.py", line 107, in <module>
    returnCode = subprocess.call(texPandocCommand)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [all] Error 1`

**Comment by julien** [comment]
Hey @benhdkn ,

Have a look at #162 

The build on OSX has been broken for a few months now 🙃

I've tried to build on Linux (Debian stable, Debian testing, Ubuntu) and no luck either.

**Comment by benhdkn** [comment]
Alright then.

I'll try to install an older version of Pandoc (< 2) and see if it gives better results.

**Comment by benhdkn** [comment]
Alternatively, I found this link on reddit for the PDF: http://easyguet.ch/temp/thebookofshaders.pdf

**Comment by julien** [comment]
Any news on this?

**Comment by zeh** [comment]
@benhdkn That is missing images.

**Comment by 0x80** [comment]
Anyone figured this out?

A shared compiled pdf with images is also very welcome of course...

I'm seeing this error output:

```sh
Generating ./book.pdf from:
        ./00/tmp.md
        ./01/tmp.md
        ./02/tmp.md
        ./03/tmp.md
        ./04/tmp.md
        ./05/tmp.md
        ./06/tmp.md
        ./07/tmp.md
        ./08/tmp.md
        ./09/tmp.md
        ./10/tmp.md
        ./11/tmp.md
        ./12/tmp.md
        ./13/tmp.md
        ./14/tmp.md
        ./15/tmp.md
        ./16/tmp.md
        ./17/tmp.md
        ./18/tmp.md
        ./appendix/tmp.md
        ./examples/tmp.md
        ./glossary/tmp.md
Using the following flags:
        -N
        --smart
        --no-tex-ligatures
        --toc
        --standalone
        --preserve-tabs
        -V documentclass=scrbook
        -V papersize=a4
        -V links-as-note
        -S
        --latex-engine=xelatex
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Unknown option --no-tex-ligatures.
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
--latex-engine has been removed.  Use --pdf-engine instead.
Try pandoc --help for more information.
Error in building of ./book.tex
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Unknown option --no-tex-ligatures.
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
--latex-engine has been removed.  Use --pdf-engine instead.
Try pandoc --help for more information.
Error in building of ./book.pdf
```

**Comment by 0x80** [comment]
@zeh At a first glance the link that @benhdkn provided does look like it contains the images. Are you missing particular ones?

**Comment by zeh** [comment]
@0x80 Yeah, the very first images in the introduction. It says "The images above were made in different ways..." but there's no images. Maybe because the right one is an embedded shader?
