### ISSUE TITLE
Confusing Variable Names

### ISSUE THREAD

**Issue by vormplus** [patriciogonzalezvivo/thebookofshaders#21]
The circle example uses a variable named l, and it looks a lot like the number 1 on the website. It might be better to change that variable name. I've lost some time figuring out that the dot() function used the l variable and not the number 1.

![bookofshaders](https://cloud.githubusercontent.com/assets/805141/10728665/11cbda24-7be4-11e5-8cc3-ce2b7c20b202.png)

**Comment by patriciogonzalezvivo** [comment]
nice observation, I will work on it

**Comment by patriciogonzalezvivo** [comment]
Could you point which examples are you referring? thanks

**Comment by vormplus** [comment]
The example where you draw a circle (http://patriciogonzalezvivo.com/2015/thebookofshaders/07/). Don't know if there are other examples with the same issue.

**Comment by patriciogonzalezvivo** [comment]
Fixed in https://github.com/patriciogonzalezvivo/thebookofshaders/commit/3d3d5fd5051372ced56ed83ba58324b8f01f75f3

Thank you!
