### ISSUE TITLE
The truchet tile example cell index

### ISSUE THREAD

**Issue by cdaein** [patriciogonzalezvivo/thebookofshaders#22]
First of all, thank you very much for this amazing project.

While I was trying a truchet tile example from this page:
http://patriciogonzalezvivo.com/2015/thebookofshaders/09/

line: 36
```c
    //      |
    //  0   |   1
    //      |
    //--------------
    //      |
    //  2   |   3
    //      |
```

I think the cell order should be:
```c
    //      |
    //  2   |   3
    //      |
    //--------------
    //      |
    //  0   |   1
    //      |
```

as it looks to me the way you set up the vertex array, the bottom-left is the (0,0).

**Comment by patriciogonzalezvivo** [comment]
Hi! I just fixed in https://github.com/patriciogonzalezvivo/thebookofshaders/commit/3d3d5fd5051372ced56ed83ba58324b8f01f75f3

Thank you!
