### ISSUE TITLE
How can I generate an epub from this?

### ISSUE THREAD

**Issue by NightMachinary** [patriciogonzalezvivo/thebookofshaders#229]

**Comment by javl** [comment]
I was able to generate a working epub simply by editing `src/parseBook.py` and changing ```pdfBookPath = os.path.join(outputPath, "book.pdf")``` at the top into ```pdfBookPath = os.path.join(outputPath, "book.epub")```.

Make sure to clone the most recent version of this repo before you try the ```make``` command, as a pull request fixing the export was just merged.
