### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Vivraan** [patriciogonzalezvivo/thebookofshaders#309]
Given that the book documentation asks the user to have Python 2.6 and that it has reached the end of its life cycle, wouldn't it be apt to change it to be compatible with at least Python 3.4?

To that end, I'm trying to compile the book for offline use on my Android phone.

EDIT: I've implemented this as #310.

**Comment by patriciogonzalezvivo** [comment]
Thanks so much!!!
