### ISSUE TITLE
fragColor is deprecated in favor of outColor 

### ISSUE THREAD

**Issue by CarlyRaeJepsenStan** [patriciogonzalezvivo/thebookofshaders#373]
https://stackoverflow.com/questions/51459596/using-gl-fragcolor-vs-out-vec4-color 

Because of this, pasting code from this book into SHADERed results in an error. Should this be considered a high or low priority problem?

**Comment by patriciogonzalezvivo** [comment]
It's not this book fault. Seams shadered is using glsl 400 or higher.

**Comment by CarlyRaeJepsenStan** [comment]
Hm...... is there a particular reason for the book using glsl <400?

**Comment by patriciogonzalezvivo** [comment]
WebGL 1.0 don't support it
