### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by TomArrow** [patriciogonzalezvivo/thebookofshaders#374]
I read the license file and I just wanted to ask for a clarification if this also applies to all the code samples. It sounds like it wouldn't even allow for copying the code samples to play around with them, much less reuse them in another project. I'm looking for some shader code I can use in a GPL v2 project. Is it fair to say that the code samples in the book of shaders are a no-go then?

**Comment by patriciogonzalezvivo** [comment]
It's ok to play around with the code. The licenses hard no is on NFT or other ways to profit from the code/text.
If you are doing experiments, just give the proper attribution.

**Comment by TomArrow** [comment]
Oh, so you're saying that anything created using the code, aka resulting images/graphics, are not allowed to be used for profit. Okay, I didn't really plan on doing that just now, but it feels like a waste of time to work with that code then since I might want to do commercial work some day. Will try to find something else, thanks for the clarification.

**Comment by patriciogonzalezvivo** [comment]
Correct, the goal of the book is to teach you to make your own code. It's an educational resource.
