### ISSUE TITLE
Dark mode for online version

### ISSUE THREAD

**Issue by nr1q** [patriciogonzalezvivo/thebookofshaders#380]
Hello, I've been reading this at night. So I think it would be nice to have a button to switch between day (light) and night (dark) mode. I just made a button using devtools and it's pretty simple. I can submit a PR if this idea is accepted.

Thanks for such a great book!

**Comment by patriciogonzalezvivo** [comment]
That would be a great feature! Thank you

**Comment by nr1q** [comment]
You'we welcome :)
