### ISSUE TITLE
book off-line instructions not work

### ISSUE THREAD

**Issue by milen-prg** [patriciogonzalezvivo/thebookofshaders#397]
On Windows 10 Pro 64bit:

I try the instructions from "How can I navigate this book off-line?":
git clone --recursive https://github.com/patriciogonzalezvivo/thebookofshaders.git
cd thebookofshaders
git submodule foreach git submodule init && git submodule update
"C:\php-8.2.2-Win32-vs16-x64\php" -S localhost:8000

And for some chapters, the browser returns error:

at start, for hello world chapter, 
Fatal error: Uncaught Error: Call to undefined function mb_strlen() in C:\Users\mlap\Downloads\temp\thebookofshaders\src\parsedown\Parsedown.php:144 Stack trace: #0 C:\Users\mlap\Downloads\temp\thebookofshaders\src\parsedown\Parsedown.php(39): Parsedown->lines(Array) #1 C:\Users\mlap\Downloads\temp\thebookofshaders\index.php(21): Parsedown->text('<canvas id="cus...') #2 {main} thrown in C:\Users\mlap\Downloads\temp\thebookofshaders\src\parsedown\Parsedown.php on line 144

chapter "[Узоры](http://localhost:8000/09/?lan=ru)",(english returns error):

Fatal error: Uncaught Error: Call to undefined function mb_strlen() in C:\Users\mlap\Downloads\temp\thebookofshaders\src\parsedown\Parsedown.php:144 Stack trace: #0 C:\Users\mlap\Downloads\temp\thebookofshaders\src\parsedown\Parsedown.php(39): Parsedown->lines(Array) #1 C:\Users\mlap\Downloads\temp\thebookofshaders\09\index.php(21): Parsedown->text('## \xD0\xA3\xD0\xB7\xD0\xBE\xD1\x80\xD1\x8B\n\n...') #2 {main} thrown in C:\Users\mlap\Downloads\temp\thebookofshaders\src\parsedown\Parsedown.php on line 144

etc.

**Comment by kyrnal** [comment]
There seems to be an issue with the submodule parsedown.
Most of the pages are functional.
The effected pages seem to be:

> http://localhost:8000/index.php
> http://localhost:8000/02 
> http://localhost:8000/09

If you navigate to the page numbers manually, the offline version is mostly there.
