### ISSUE TITLE
Making PDF or offline version

### ISSUE THREAD

**Issue by comscandiumplumbumd** [patriciogonzalezvivo/thebookofshaders#4]
Thank you for a nice book!

Currently, the "Make a PDF of the book to print" and "Make a off-line version of this book on [About this Book](http://patriciogonzalezvivo.com/2015/thebookofshaders//00/) section lead to 404. Is this intended?

**Comment by patriciogonzalezvivo** [comment]
I just push a fix for this. Thanks!
