### ISSUE TITLE
Precompile the book to PDF and EPUB

### ISSUE THREAD

**Issue by lu2000luk** [patriciogonzalezvivo/thebookofshaders#416]
Just make a folder called "book" containing the 2 files, why do i have to compile it myself just to read it on my kindle?

**Comment by bartcode** [comment]
I'd say because then the repo would get rather big over time. But setting up a build pipeline here that creates a release with the epub/pdf would work.

**Comment by lu2000luk** [comment]
You can use a workflow or even a little website you can host on netlify that (when called with a github webhook) builds the book and make you able to download it

**Comment by xmha97** [comment]
+1
