### ISSUE TITLE
2015/thebookofshaders/06/easing.frag 404s

### ISSUE THREAD

**Issue by brannondorsey** [patriciogonzalezvivo/thebookofshaders#42]
Finally getting around to reading through this glorious book. Amazing stuff, thanks for all of your hard work :smile_cat:.

I've noticed that in chapeter 06, the easing example 404s in the editor with:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /2015/thebookofshaders/06/easing.frag was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at patriciogonzalezvivo.com Port 80</address>
</body></html>
```
Looks like this file is missing: http://patriciogonzalezvivo.com/2015/thebookofshaders/06/easing.frag

Thanks again for the awesome resource!

**Comment by patriciogonzalezvivo** [comment]
Thanks for noticing! i put it back... don't really know why wasn't there : /
