### ISSUE TITLE
How to remap in Shape chapter 

### ISSUE THREAD

**Issue by flush11** [patriciogonzalezvivo/thebookofshaders#47]
It's about the code in "Useful properties of a Distance Field" in Shape chapter

[http://patriciogonzalezvivo.com/2015/thebookofshaders/07/](http://patriciogonzalezvivo.com/2015/thebookofshaders/07/)

To remap the coordinate, the following code is used.

```
vec2 st = gl_FragCoord.xy/u_resolution.xy;
st.x *= u_resolution.x/u_resolution.y;
st = st *2.-1.; 
```

It depends on the intention, but I think the following is widely applicable (especially if you think about the billboard which is not square but rectangle.)

```
vec2 st = (2.0 * gl_FragCoord.xy - u_resolution.xy) / min(u_resolution.x, u_resolution.y);
```

**Comment by patriciogonzalezvivo** [comment]
Hello! Definitely is better, I will leave the old cold like is for new coders... I have experience in the past that students get lost with one-liners.
Great suggestion, thanks!
