### ISSUE TITLE
u_mouse y calculation inverts sign

### ISSUE THREAD

**Issue by codebje** [patriciogonzalezvivo/thebookofshaders#5]
https://github.com/patriciogonzalezvivo/thebookofshaders/blob/master/src/glslCanvas.js#L458

... -mouse.y-rect.top … should be either -(mouse.y - rect.top) or -mouse.y+rect.top; the further the rect is from 0px, the more negative the u_mouse.y value becomes.

**Comment by patriciogonzalezvivo** [comment]
Fixed! Thanks a lot!
