### ISSUE TITLE
changing the code from examples

### ISSUE THREAD

**Issue by amorenoc** [patriciogonzalezvivo/thebookofshaders#53]
> If you are reading this book in a browser the previous block of code is interactive. That means you can click and change any part of the code you want to explore. Changes will be updated immediately thanks to the GPU architecture that compiles and replaces shaders on the fly. Give it a try by changing the values on line 6.

I can see the code using devtools, but I guess that's not the idea :)
What am I missing?

**Comment by necsoft** [comment]
Hello @amorenoc, this is the normal behavior on Chrome:

![livecode](https://cloud.githubusercontent.com/assets/1678333/13522246/20f321d4-e1cd-11e5-9f9f-fb3502833b6f.gif)

Which Browser and OS are you using?

**Comment by amorenoc** [comment]
@necsoft I just can see the canvas, but not the editor. I am using Chrome 49.0.2623.75 on OSX El Captian. I tried Safari too, and got the same result.

**Comment by patriciogonzalezvivo** [comment]
Hello @amorenoc, I just fix it. Thanks for reporting this bug.

**Comment by amorenoc** [comment]
great job, thanks!
