### ISSUE TITLE
safari web content

### ISSUE THREAD

**Issue by niteswim** [patriciogonzalezvivo/thebookofshaders#55]
Hello -
Every time I pull up GLSL Editor, Safari Web Content crashes.
This is a recent predicament.
Whenever I attempted opening in Chrome, it opened up but the editor started flashing blue.

**Comment by patriciogonzalezvivo** [comment]
Thanks for reporting it....
I was aware the one on safari...
But I didn't knew about the blue flash on chrome
Any error console?
Could you make a screenshot of it? or a gif? Thanks

**Comment by niteswim** [comment]
Np!
Well this time when I opened an example it was green, and you could move it and when you did it left horizontal lines in its wake like so! (See attached.) No error console however.
<img width="1043" alt="screen shot 2016-03-16 at 4 12 11 pm" src="https://cloud.githubusercontent.com/assets/11263659/13828918/29631c92-eb92-11e5-9489-3e3542cc6d9c.png">

**Comment by patriciogonzalezvivo** [comment]
: S that's pretty horrible... I will do some research. Sorry for the inconvenient

**Comment by niteswim** [comment]
Lil buggy ;b It's alright thanks for being prompt about responding! I thought it was my computer for an instant haha.

**Comment by patriciogonzalezvivo** [comment]
Hi! There was a parallel problem with glslCanvas... can you try again on chrome?

**Comment by niteswim** [comment]
It works flawlessly now! Thank you! (:

**Comment by patriciogonzalezvivo** [comment]
Thanks you!

**Comment by polyrhythmatic** [comment]
I'm having this issue as well in Safari just so you are aware.
