### ISSUE TITLE
compile on ubuntu and pdf creation

### ISSUE THREAD

**Issue by toastbrotch** [patriciogonzalezvivo/thebookofshaders#6]
hi
i'd love to read your book on my mobile while traveling. so i tried to create the pdf on my ubuntu14.10 workstation (no raspy around). 

it seems that some images are missing: 
```
pandoc: Could not find image `./02/tmp-hello_world.png', skipping...
pandoc: Could not find image `./03/tmp-time.png', skipping...
pandoc: Could not find image `./03/tmp-space.png', skipping...
pandoc: Could not find image `./05/tmp-linear.png', skipping...
pandoc: Could not find image `./05/tmp-expo.png', skipping...
pandoc: Could not find image `./05/tmp-step.png', skipping...
pandoc: Could not find image `./05/tmp-smoothstep.png', skipping...
```

i've set up the my machine to compile your book like this:
```
sudo apt-get install git-core libfreeimage-dev texlive-xetex pandoc texlive-fonts-recommended texlive-latex-extra
git clone https://github.com/patriciogonzalezvivo/thebookofshaders.git
cd thebookofshaders
make
```

but i was not yet able to compile the glslViewer (bcm_host.h missing)... as far as i understand glslViewer is needed to create the missing images above?

thanx and cheers.ivo

**Comment by patriciogonzalezvivo** [comment]
Hi, glslViewer is the one makes the images from the shaders files. Without it is not possible to compile the book.

I should port glslViewer soon. keep in touch

**Comment by toastbrotch** [comment]
hi. cool thanx
meanwhile i found a quick and dirty hack how to compile the book (with some images missing):
```
wget http://upload.wikimedia.org/wikipedia/commons/c/ca/1x1.png
sed -i 's/shaderCommand = .*$/shaderCommand = "cp 1x1.png  " + shaderImage/' src/parseBook.py
sed -i 's/sincos\.gif/sincos.png/' 05/README.md 05/tmp.md book.tex
make
```
