### ISSUE TITLE
What does "pct" mean?

### ISSUE THREAD

**Issue by donmccurdy** [patriciogonzalezvivo/thebookofshaders#62]
You use `pct` throughout your examples, and I assume that's a standard GLSL term, but I can't seem to find a definition in the book. Is that an acronym?

**Comment by patriciogonzalezvivo** [comment]
Hello, thanks for your question. Is not a GLSL standard just the acronym of percentage (https://en.wikipedia.org/wiki/Percentage) : )

**Comment by donmccurdy** [comment]
Thanks, makes sense now that you point it out!
