### ISSUE TITLE
"More" link on examples page is broken

### ISSUE THREAD

**Issue by stuaxo** [patriciogonzalezvivo/thebookofshaders#99]
Hi,
  Thanks for the book of shaders, it is fantastic :)

I found a missing link - 

To reproduce go to the page below and click "more"

http://patriciogonzalezvivo.com/2015/thebookofshaders/examples/

**Comment by patriciogonzalezvivo** [comment]
hooo I see...

It ment to be seen on http://thebookofshaders.com/examples/ 

I should find a way to redirect all entries to http://patriciogonzalezvivo.com/2015/thebookofshaders to http://thebookofshaders.com . Any idea how to do that?

Thanks for the heads up

**Comment by stuaxo** [comment]
Good question...    if you are on Apache then you can probably use modalias to setup a rule for this

http://httpd.apache.org/docs/current/rewrite/avoid.html#redirect

(or modrewrite if you need a more complex rule)

If you are using something like wordpress there might be a plugin you can install to do it.

**Comment by patriciogonzalezvivo** [comment]
I'm using Apache.... but I don't want to mess with google analytics... any idea?

**Comment by stuaxo** [comment]
I have no idea about google analytics unfortunately.

Will having a 301 redirect cause a problem with them ?

http://www.inmotionhosting.com/support/website/redirects/setting-up-a-301-permanent-redirect-via-htaccess


There is some info here about making taking the url with a utm parameter, but since I don't know about GA, I have no idea how relevant it is

https://moz.com/community/q/tracking-301-redirect-traffic-in-google-analytics

**Comment by patriciogonzalezvivo** [comment]
Done!! : )

Thanks!

**Comment by stuaxo** [comment]
Fixed this, end - nice.
